// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: services/domains/proto/domains.proto

package domains

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ListDomainsRequest struct {
	PageSize             int32    `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken            string   `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListDomainsRequest) Reset()         { *m = ListDomainsRequest{} }
func (m *ListDomainsRequest) String() string { return proto.CompactTextString(m) }
func (*ListDomainsRequest) ProtoMessage()    {}
func (*ListDomainsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15fe4e2bc1c86bf4, []int{0}
}
func (m *ListDomainsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDomainsRequest.Unmarshal(m, b)
}
func (m *ListDomainsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDomainsRequest.Marshal(b, m, deterministic)
}
func (m *ListDomainsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDomainsRequest.Merge(m, src)
}
func (m *ListDomainsRequest) XXX_Size() int {
	return xxx_messageInfo_ListDomainsRequest.Size(m)
}
func (m *ListDomainsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDomainsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListDomainsRequest proto.InternalMessageInfo

func (m *ListDomainsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListDomainsRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

type ListDomainsResponse struct {
	Domains              []*Domain `protobuf:"bytes,1,rep,name=domains,proto3" json:"domains,omitempty"`
	TotalSize            int32     `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	NextPageToken        string    `protobuf:"bytes,3,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListDomainsResponse) Reset()         { *m = ListDomainsResponse{} }
func (m *ListDomainsResponse) String() string { return proto.CompactTextString(m) }
func (*ListDomainsResponse) ProtoMessage()    {}
func (*ListDomainsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_15fe4e2bc1c86bf4, []int{1}
}
func (m *ListDomainsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDomainsResponse.Unmarshal(m, b)
}
func (m *ListDomainsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDomainsResponse.Marshal(b, m, deterministic)
}
func (m *ListDomainsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDomainsResponse.Merge(m, src)
}
func (m *ListDomainsResponse) XXX_Size() int {
	return xxx_messageInfo_ListDomainsResponse.Size(m)
}
func (m *ListDomainsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDomainsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListDomainsResponse proto.InternalMessageInfo

func (m *ListDomainsResponse) GetDomains() []*Domain {
	if m != nil {
		return m.Domains
	}
	return nil
}

func (m *ListDomainsResponse) GetTotalSize() int32 {
	if m != nil {
		return m.TotalSize
	}
	return 0
}

func (m *ListDomainsResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type GetDomainRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDomainRequest) Reset()         { *m = GetDomainRequest{} }
func (m *GetDomainRequest) String() string { return proto.CompactTextString(m) }
func (*GetDomainRequest) ProtoMessage()    {}
func (*GetDomainRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15fe4e2bc1c86bf4, []int{2}
}
func (m *GetDomainRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDomainRequest.Unmarshal(m, b)
}
func (m *GetDomainRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDomainRequest.Marshal(b, m, deterministic)
}
func (m *GetDomainRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDomainRequest.Merge(m, src)
}
func (m *GetDomainRequest) XXX_Size() int {
	return xxx_messageInfo_GetDomainRequest.Size(m)
}
func (m *GetDomainRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDomainRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDomainRequest proto.InternalMessageInfo

func (m *GetDomainRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type CreateDomainRequest struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDomainRequest) Reset()         { *m = CreateDomainRequest{} }
func (m *CreateDomainRequest) String() string { return proto.CompactTextString(m) }
func (*CreateDomainRequest) ProtoMessage()    {}
func (*CreateDomainRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15fe4e2bc1c86bf4, []int{3}
}
func (m *CreateDomainRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDomainRequest.Unmarshal(m, b)
}
func (m *CreateDomainRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDomainRequest.Marshal(b, m, deterministic)
}
func (m *CreateDomainRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDomainRequest.Merge(m, src)
}
func (m *CreateDomainRequest) XXX_Size() int {
	return xxx_messageInfo_CreateDomainRequest.Size(m)
}
func (m *CreateDomainRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDomainRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDomainRequest proto.InternalMessageInfo

func (m *CreateDomainRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreateDomainRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type UpdateDomainRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateDomainRequest) Reset()         { *m = UpdateDomainRequest{} }
func (m *UpdateDomainRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateDomainRequest) ProtoMessage()    {}
func (*UpdateDomainRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15fe4e2bc1c86bf4, []int{4}
}
func (m *UpdateDomainRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateDomainRequest.Unmarshal(m, b)
}
func (m *UpdateDomainRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateDomainRequest.Marshal(b, m, deterministic)
}
func (m *UpdateDomainRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateDomainRequest.Merge(m, src)
}
func (m *UpdateDomainRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateDomainRequest.Size(m)
}
func (m *UpdateDomainRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateDomainRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateDomainRequest proto.InternalMessageInfo

func (m *UpdateDomainRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *UpdateDomainRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UpdateDomainRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type DeleteDomainRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDomainRequest) Reset()         { *m = DeleteDomainRequest{} }
func (m *DeleteDomainRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteDomainRequest) ProtoMessage()    {}
func (*DeleteDomainRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15fe4e2bc1c86bf4, []int{5}
}
func (m *DeleteDomainRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDomainRequest.Unmarshal(m, b)
}
func (m *DeleteDomainRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDomainRequest.Marshal(b, m, deterministic)
}
func (m *DeleteDomainRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDomainRequest.Merge(m, src)
}
func (m *DeleteDomainRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteDomainRequest.Size(m)
}
func (m *DeleteDomainRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDomainRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDomainRequest proto.InternalMessageInfo

func (m *DeleteDomainRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type Domain struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Domain) Reset()         { *m = Domain{} }
func (m *Domain) String() string { return proto.CompactTextString(m) }
func (*Domain) ProtoMessage()    {}
func (*Domain) Descriptor() ([]byte, []int) {
	return fileDescriptor_15fe4e2bc1c86bf4, []int{6}
}
func (m *Domain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Domain.Unmarshal(m, b)
}
func (m *Domain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Domain.Marshal(b, m, deterministic)
}
func (m *Domain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Domain.Merge(m, src)
}
func (m *Domain) XXX_Size() int {
	return xxx_messageInfo_Domain.Size(m)
}
func (m *Domain) XXX_DiscardUnknown() {
	xxx_messageInfo_Domain.DiscardUnknown(m)
}

var xxx_messageInfo_Domain proto.InternalMessageInfo

func (m *Domain) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Domain) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Domain) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto.RegisterType((*ListDomainsRequest)(nil), "domains.ListDomainsRequest")
	proto.RegisterType((*ListDomainsResponse)(nil), "domains.ListDomainsResponse")
	proto.RegisterType((*GetDomainRequest)(nil), "domains.GetDomainRequest")
	proto.RegisterType((*CreateDomainRequest)(nil), "domains.CreateDomainRequest")
	proto.RegisterType((*UpdateDomainRequest)(nil), "domains.UpdateDomainRequest")
	proto.RegisterType((*DeleteDomainRequest)(nil), "domains.DeleteDomainRequest")
	proto.RegisterType((*Domain)(nil), "domains.Domain")
}

func init() {
	proto.RegisterFile("services/domains/proto/domains.proto", fileDescriptor_15fe4e2bc1c86bf4)
}

var fileDescriptor_15fe4e2bc1c86bf4 = []byte{
	// 487 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xe5, 0x84, 0xfe, 0xf1, 0x24, 0x55, 0xc2, 0xa4, 0x6a, 0x83, 0xd3, 0x4a, 0xd1, 0x0a,
	0x55, 0x69, 0x0f, 0xb6, 0x28, 0x37, 0x8e, 0xd0, 0x8a, 0x4b, 0x0f, 0x91, 0x4b, 0x0f, 0x54, 0x48,
	0xc5, 0xc5, 0x43, 0xb4, 0x22, 0xf5, 0x9a, 0xec, 0xa6, 0x82, 0x22, 0x2e, 0x5c, 0x78, 0x00, 0x1e,
	0x0d, 0x1e, 0x81, 0x07, 0x41, 0xde, 0xf5, 0xba, 0x9b, 0xc4, 0x48, 0x1c, 0xb8, 0x79, 0x76, 0xc6,
	0xbf, 0xf9, 0x46, 0xdf, 0x0c, 0x3c, 0x96, 0x34, 0xbb, 0xe5, 0xef, 0x48, 0x46, 0xa9, 0xb8, 0x49,
	0x78, 0x26, 0xa3, 0x7c, 0x26, 0x94, 0xb0, 0x51, 0xa8, 0x23, 0xdc, 0x28, 0xc3, 0x60, 0x6f, 0x22,
	0xc4, 0x64, 0x4a, 0x51, 0x92, 0xf3, 0x28, 0xc9, 0x32, 0xa1, 0x12, 0xc5, 0x85, 0x2d, 0x0b, 0x06,
	0x65, 0x56, 0x47, 0xd7, 0xf3, 0xf7, 0x11, 0xdd, 0xe4, 0xea, 0xb3, 0x49, 0xb2, 0x31, 0xe0, 0x19,
	0x97, 0xea, 0xc4, 0x90, 0x62, 0xfa, 0x38, 0x27, 0xa9, 0x70, 0x00, 0x7e, 0x9e, 0x4c, 0xe8, 0x4a,
	0xf2, 0x3b, 0xea, 0x7b, 0x43, 0x6f, 0xb4, 0x16, 0x6f, 0x16, 0x0f, 0xe7, 0xfc, 0x8e, 0x70, 0x1f,
	0x40, 0x27, 0x95, 0xf8, 0x40, 0x59, 0xbf, 0x31, 0xf4, 0x46, 0x7e, 0xac, 0xcb, 0x5f, 0x15, 0x0f,
	0xec, 0xbb, 0x07, 0xbd, 0x05, 0xa4, 0xcc, 0x45, 0x26, 0x09, 0x0f, 0xc1, 0xea, 0xed, 0x7b, 0xc3,
	0xe6, 0xa8, 0x75, 0xdc, 0x09, 0xed, 0x38, 0xa6, 0x34, 0xb6, 0xf9, 0xa2, 0x83, 0x12, 0x2a, 0x99,
	0x9a, 0xfe, 0x0d, 0xdd, 0xdf, 0xd7, 0x2f, 0x5a, 0xc0, 0x01, 0x74, 0x32, 0xfa, 0xa4, 0xae, 0x1c,
	0x15, 0x4d, 0xad, 0x62, 0xab, 0x78, 0x1e, 0x57, 0x4a, 0x0e, 0xa0, 0xfb, 0x92, 0x4a, 0x1d, 0x76,
	0x32, 0x84, 0x07, 0xf3, 0x39, 0x4f, 0xf5, 0x50, 0x7e, 0xac, 0xbf, 0xd9, 0x29, 0xf4, 0x5e, 0xcc,
	0x28, 0x51, 0xb4, 0x58, 0xba, 0x0d, 0x6b, 0x8a, 0xab, 0x29, 0x95, 0xb5, 0x26, 0xc0, 0x3e, 0x6c,
	0x24, 0x69, 0x3a, 0x23, 0x29, 0xcb, 0xd1, 0x6d, 0xc8, 0x5e, 0x43, 0xef, 0x22, 0x4f, 0x57, 0x30,
	0x35, 0x1d, 0xef, 0xd1, 0x8d, 0xbf, 0xa0, 0x9b, 0x8b, 0xe8, 0x43, 0xe8, 0x9d, 0xd0, 0x94, 0xfe,
	0x01, 0xcd, 0xce, 0x60, 0xdd, 0x14, 0xfd, 0x8f, 0xc6, 0xc7, 0xbf, 0x9a, 0xb0, 0x65, 0x70, 0xe7,
	0x66, 0x23, 0xf1, 0x12, 0x5a, 0x8e, 0xbb, 0x38, 0xa8, 0x4c, 0x5c, 0x5d, 0xa3, 0x60, 0xaf, 0x3e,
	0x69, 0x16, 0x82, 0x75, 0xbf, 0xfd, 0xfc, 0xfd, 0xa3, 0x01, 0xb8, 0x69, 0xd7, 0x1a, 0xc7, 0xe0,
	0x57, 0x86, 0xe1, 0xa3, 0xea, 0xe7, 0x65, 0x13, 0x83, 0xe5, 0xcd, 0x61, 0xbb, 0x1a, 0xf5, 0x10,
	0x3b, 0xd5, 0xbd, 0x7c, 0x29, 0xc6, 0xfd, 0x8a, 0x17, 0xd0, 0x76, 0xad, 0xc5, 0x7b, 0x45, 0x35,
	0x8e, 0xaf, 0x72, 0x77, 0x34, 0xb7, 0xcb, 0x5a, 0xd1, 0xed, 0x13, 0x8b, 0x7e, 0xe6, 0x1d, 0xe1,
	0x1b, 0x68, 0xbb, 0x56, 0x3b, 0xd8, 0x9a, 0x0d, 0x58, 0xc5, 0xee, 0x6b, 0xec, 0x6e, 0x80, 0x0e,
	0xb6, 0x54, 0x5c, 0xd0, 0xdf, 0x42, 0xdb, 0x75, 0xdb, 0xa1, 0xd7, 0x2c, 0x41, 0xb0, 0x13, 0x9a,
	0xfb, 0x0e, 0xed, 0x7d, 0x87, 0xa7, 0xc5, 0x7d, 0xb3, 0x40, 0x37, 0xd9, 0x3e, 0xaa, 0x69, 0xf2,
	0xdc, 0xbf, 0xb4, 0xb7, 0x76, 0xbd, 0xae, 0x7f, 0x7b, 0xfa, 0x27, 0x00, 0x00, 0xff, 0xff, 0x17,
	0xf8, 0xc6, 0x2a, 0x73, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DomainServiceClient is the client API for DomainService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DomainServiceClient interface {
	// List Domains
	ListDomains(ctx context.Context, in *ListDomainsRequest, opts ...grpc.CallOption) (*ListDomainsResponse, error)
	// Get Domain
	GetDomain(ctx context.Context, in *GetDomainRequest, opts ...grpc.CallOption) (*Domain, error)
	// Create Domain object request
	CreateDomain(ctx context.Context, in *CreateDomainRequest, opts ...grpc.CallOption) (*Domain, error)
	// Update Domain object request
	UpdateDomain(ctx context.Context, in *UpdateDomainRequest, opts ...grpc.CallOption) (*Domain, error)
	// Delete Domain object request
	DeleteDomain(ctx context.Context, in *DeleteDomainRequest, opts ...grpc.CallOption) (*types.Empty, error)
}

type domainServiceClient struct {
	cc *grpc.ClientConn
}

func NewDomainServiceClient(cc *grpc.ClientConn) DomainServiceClient {
	return &domainServiceClient{cc}
}

func (c *domainServiceClient) ListDomains(ctx context.Context, in *ListDomainsRequest, opts ...grpc.CallOption) (*ListDomainsResponse, error) {
	out := new(ListDomainsResponse)
	err := c.cc.Invoke(ctx, "/domains.DomainService/ListDomains", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *domainServiceClient) GetDomain(ctx context.Context, in *GetDomainRequest, opts ...grpc.CallOption) (*Domain, error) {
	out := new(Domain)
	err := c.cc.Invoke(ctx, "/domains.DomainService/GetDomain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *domainServiceClient) CreateDomain(ctx context.Context, in *CreateDomainRequest, opts ...grpc.CallOption) (*Domain, error) {
	out := new(Domain)
	err := c.cc.Invoke(ctx, "/domains.DomainService/CreateDomain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *domainServiceClient) UpdateDomain(ctx context.Context, in *UpdateDomainRequest, opts ...grpc.CallOption) (*Domain, error) {
	out := new(Domain)
	err := c.cc.Invoke(ctx, "/domains.DomainService/UpdateDomain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *domainServiceClient) DeleteDomain(ctx context.Context, in *DeleteDomainRequest, opts ...grpc.CallOption) (*types.Empty, error) {
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, "/domains.DomainService/DeleteDomain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DomainServiceServer is the server API for DomainService service.
type DomainServiceServer interface {
	// List Domains
	ListDomains(context.Context, *ListDomainsRequest) (*ListDomainsResponse, error)
	// Get Domain
	GetDomain(context.Context, *GetDomainRequest) (*Domain, error)
	// Create Domain object request
	CreateDomain(context.Context, *CreateDomainRequest) (*Domain, error)
	// Update Domain object request
	UpdateDomain(context.Context, *UpdateDomainRequest) (*Domain, error)
	// Delete Domain object request
	DeleteDomain(context.Context, *DeleteDomainRequest) (*types.Empty, error)
}

// UnimplementedDomainServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDomainServiceServer struct {
}

func (*UnimplementedDomainServiceServer) ListDomains(ctx context.Context, req *ListDomainsRequest) (*ListDomainsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDomains not implemented")
}
func (*UnimplementedDomainServiceServer) GetDomain(ctx context.Context, req *GetDomainRequest) (*Domain, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDomain not implemented")
}
func (*UnimplementedDomainServiceServer) CreateDomain(ctx context.Context, req *CreateDomainRequest) (*Domain, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDomain not implemented")
}
func (*UnimplementedDomainServiceServer) UpdateDomain(ctx context.Context, req *UpdateDomainRequest) (*Domain, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDomain not implemented")
}
func (*UnimplementedDomainServiceServer) DeleteDomain(ctx context.Context, req *DeleteDomainRequest) (*types.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDomain not implemented")
}

func RegisterDomainServiceServer(s *grpc.Server, srv DomainServiceServer) {
	s.RegisterService(&_DomainService_serviceDesc, srv)
}

func _DomainService_ListDomains_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDomainsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DomainServiceServer).ListDomains(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/domains.DomainService/ListDomains",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DomainServiceServer).ListDomains(ctx, req.(*ListDomainsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DomainService_GetDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DomainServiceServer).GetDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/domains.DomainService/GetDomain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DomainServiceServer).GetDomain(ctx, req.(*GetDomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DomainService_CreateDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DomainServiceServer).CreateDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/domains.DomainService/CreateDomain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DomainServiceServer).CreateDomain(ctx, req.(*CreateDomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DomainService_UpdateDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DomainServiceServer).UpdateDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/domains.DomainService/UpdateDomain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DomainServiceServer).UpdateDomain(ctx, req.(*UpdateDomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DomainService_DeleteDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DomainServiceServer).DeleteDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/domains.DomainService/DeleteDomain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DomainServiceServer).DeleteDomain(ctx, req.(*DeleteDomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DomainService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "domains.DomainService",
	HandlerType: (*DomainServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListDomains",
			Handler:    _DomainService_ListDomains_Handler,
		},
		{
			MethodName: "GetDomain",
			Handler:    _DomainService_GetDomain_Handler,
		},
		{
			MethodName: "CreateDomain",
			Handler:    _DomainService_CreateDomain_Handler,
		},
		{
			MethodName: "UpdateDomain",
			Handler:    _DomainService_UpdateDomain_Handler,
		},
		{
			MethodName: "DeleteDomain",
			Handler:    _DomainService_DeleteDomain_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/domains/proto/domains.proto",
}
