apiVersion: v0.1
server:
  host: 0.0.0.0
  httpPort: 8080
  grpcPort: 9090

db:
  engine: postgres
  host: localhost
  port: 5432
  db: task_manager
  user: postgres
  password: postgres
  timeZone: Europe/Stockholm

redis:
  host: 127.0.0.1
  port: 6379
  user: redis
  password: redis


